global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kairoai'
    static_configs:
      - targets: ['kairoai:5000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'bitcoin'
    static_configs:
      - targets: ['kairoai:8332']
    metrics_path: '/metrics'
    scheme: 'http'
    basic_auth:
      username: '${BITCOIN_RPC_USER}'
      password: '${BITCOIN_RPC_PASSWORD}'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml" 